name: 'TBS'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '8 0,7,14 * * *'

jobs:
  tbs:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests
      - name: 'Start Sign'
        env:
          BDUSS: ${{ secrets.BDUSS }}
        run: python main.py
